### ISSUE TITLE
[meta] Indicator improvements

### ISSUE THREAD

**Issue by kenorb** [EA31337/EA31337-classes#529]
- [x] https://github.com/EA31337/EA31337-classes/issues/522
- [x] https://github.com/EA31337/EA31337-classes/issues/552
- [x] https://github.com/EA31337/EA31337-classes/issues/523
- [x] https://github.com/EA31337/EA31337-classes/issues/524
- [x] https://github.com/EA31337/EA31337-classes/issues/525
- [x] https://github.com/EA31337/EA31337-classes/issues/526
- [x] https://github.com/EA31337/EA31337-classes/issues/527
- [x] https://github.com/EA31337/EA31337-classes/issues/528
- [ ] https://github.com/EA31337/EA31337-classes/issues/530
- [ ] https://github.com/EA31337/EA31337-classes/issues/531
- [ ] https://github.com/EA31337/EA31337-classes/issues/532
- [ ] https://github.com/EA31337/EA31337-classes/issues/533
- [ ] https://github.com/EA31337/EA31337-classes/issues/534
- [ ] https://github.com/EA31337/EA31337-classes/issues/535
- [ ] https://github.com/EA31337/EA31337-classes/issues/536
- [ ] https://github.com/EA31337/EA31337-classes/issues/537
- [ ] https://github.com/EA31337/EA31337-classes/issues/538
- [ ] https://github.com/EA31337/EA31337-classes/issues/539
